
import { Nunito } from 'next/font/google'

import './globals.css';
import Header from '@/app/components/Header/header'
import Footer from '@/app/components/Footer/footer'
import BreadcrumbComponent from '@/app/components/Common/breadcrumb'

const fontBase = Nunito({ subsets: ['latin'] })

export const metadata = {
  title: 'Zoe-997 page',
  description: 'Generated by create Mdc Team',
}

export default async function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${fontBase.className} bg-[#f5f5f5]`} suppressHydrationWarning={true}>
        <Header />
        <main id="page-main" className='px-[48px]'>
          <BreadcrumbComponent/>
          <div className='bg-white min-h-[300px] rounded-2xl p-5'>{children}</div>
        </main>
        <Footer/>
      </body>
    </html>
  )
}