
import { Nunito } from 'next/font/google'
import { Layout, theme } from 'antd';

import './globals.css';
import Header from '@/app/components/Header/header'
import Footer from '@/app/components/Footer/footer'
import BreadcrumbComponent from '@/app/components/Common/breadcrumb'
const { Content } = Layout;

const fontBase = Nunito({ subsets: ['latin'] })

export const metadata = {
  title: 'Booking Room - NextJs 13',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const {
    token: { colorBgContainer, borderRadiusLG },
  } = theme.useToken();

  return (
    <html lang="en">
      <body className={fontBase.className} suppressHydrationWarning={true}>
        <Header />
        <Content id="page-main" className='py-[48px]'>
          <div className={`bg-[${colorBgContainer}] min-h-[280px] p-[24px] rounded-[${borderRadiusLG}]`}>
            {children}
          </div>
        </Content>
        <Footer/>
      </body>
    </html>
  )
}